spring:
  data:
    mongodb:
      uri: mongodb://studyuser:1234@localhost/study?authSource=admin
  application:
    name: observation-webflux-app

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, beans

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: debug
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: debug
    org.zalando.logbook: trace
  file:
    path: /Users/emart/docker/log/observation/webflux
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${pid}){magenta} %clr(---){faint} %clr([${spring.application.name:}]){faint} %clr([%15.15t]){faint} %clr([%32X{traceId:-}-%16X{spanId:-}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

logbook:
  filter:
    enabled: true
