spring:
  data:
    mongodb:
      uri: mongodb://studyuser:1234@localhost/study?authSource=admin
  application:
    name: observation-webflux-app

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, beans

logbook:
  filter:
    enabled: true
