spring:
  data:
    mongodb:
      uri: mongodb://studyuser:1234@localhost/study?authSource=admin
  application:
    name: observation-mvc-app

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

