spring:
  data:
    mongodb:
      uri: mongodb://studyuser:1234@localhost/study?authSource=admin
  application:
    name: observation-mvc-app

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.springframework.web.client.RestTemplate: debug
    org.springframework.web.client.RestClient: debug
    org.zalando.logbook: trace
  file:
    path: /Users/emart/docker/log/observation/mvc
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${pid}){magenta} %clr(---){faint} %clr([${spring.application.name:}]){faint} %clr([%15.15t]){faint} %clr([%32X{traceId:-}-%16X{spanId:-}]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

