spring:
  application:
    name: mvc-application
  datasource:
    url: jdbc:mariadb://localhost:3306/study
    driver-class-name: org.mariadb.jdbc.Driver
    username: studyuser
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      url: redis://localhost:6379
