spring:
  application:
    name: mvc-application
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=study;trustServerCertificate=false;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: studyuser
    password: $a123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  data:
    redis:
      url: redis://localhost:6379
