spring:
  data:
    mongodb:
      uri: mongodb://studyuser:1234@localhost/study?authSource=admin
  redis:
    url: redis://localhost:6379

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
