version: "3.8"

services:
  maria-db:
    image: mariadb:11
    ports:
      - "3306:3306"
    volumes:
      - maria-db-volume:/var/lib/mysql:Z
    environment:
      - MARIADB_ROOT_PASSWORD=1234

  mongo-db:
    image: mongo:7.0-rc
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/usr/local/etc/redis

volumes:
  maria-db-volume:
  mongo-db-volume:
  redis-volume:
